### PR TITLE
WIP: Scopes for roles

### PR DESCRIPTION
**Pull request by badlamer**
Create scopes and resolvers for roles.
What do you think of it?

There is no way to write tests.

### CODE REVIEW

**Comment by pokonski** [comment]
Can you show an example what's it about and why do you think AG needs it? The code doesn't say much.

> There is no way to write tests.

There is always a way :)

**Comment by badlamer** [comment]
Example. This for different object scopes for different user roles.

```ruby
class MemberRole < AccessGranted::Role
  def configure
    can :create, Post
    can :destroy, Post do |post, user|
      post.author == user
    end

    scope :my_posts, Post do |criteria, user|
      criteria.where(author_id: user.id)
    end
  end
end

class AdminRole < AccessGranted::Role
   scope :my_posts, Post
end

class PostsController
  def show
    @posts = resolve :my_posts, Post.where(published: true) # support base object or criteria
  end
end

```

**Comment by badlamer** [comment]
Made like [this](https://github.com/elabs/pundit#scopes), but for different roles.

**Comment by badlamer** [comment]
ping @pokonski

**Pull request closed without merging**
