### PR TITLE
Ability usage with grape

### PR DESCRIPTION
**Pull request by badlamer**
Similar to https://github.com/CanCanCommunity/cancancan/blob/develop/lib/cancan/controller_additions.rb#L297

### CODE REVIEW

**Comment by pokonski** [comment]
hi @badlamer. Thanks for the PR. Does it crash for you when including in Grape projects without this change?

**Comment by badlamer** [comment]
This works with Grape and ApplicationCable::Channel.
Without changes grape NoMethodError (undefined method `helper_method' for #<Module>) when execute 

```ruby
class API < Grape::API
  helpers AccessGranted::Rails::ControllerMethods
end
```

**Comment by pokonski** [comment]
Cool, let's merge it then! Time for me to add those hooks to support Grape out of the box :)

**Comment by pokonski** [comment]
I just released `1.0.2` version with your fix, thanks for the report and keep the bug fixes coming!

**Pull request merged**
